import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { SeedwingDogmaGeneratedModule, SeedwingDogmaGeneratedSharedModule } from './generated/module';
import { SeedwingDogmaValidator, registerValidationChecks } from './seedwing-dogma-validator';
import { SeedwingDogmaSemanticTokenProvider } from './seedwing-dogma-semantic-tokens';
import { SeedwingDogmaScopeProvider } from './seedwing-dogma-scope-provider';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SeedwingDogmaAddedServices = {
    validation: {
        SeedwingDogmaValidator: SeedwingDogmaValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SeedwingDogmaServices = LangiumServices & SeedwingDogmaAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SeedwingDogmaModule: Module<SeedwingDogmaServices, PartialLangiumServices & SeedwingDogmaAddedServices> = {
    validation: {
        SeedwingDogmaValidator: () => new SeedwingDogmaValidator()
    },
    references: {
        ScopeProvider: (services) => new SeedwingDogmaScopeProvider(services)
    },
    lsp: {
        SemanticTokenProvider: (services) => new SeedwingDogmaSemanticTokenProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSeedwingDogmaServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SeedwingDogma: SeedwingDogmaServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SeedwingDogmaGeneratedSharedModule
    );
    const SeedwingDogma = inject(
        createDefaultModule({ shared }),
        SeedwingDogmaGeneratedModule,
        SeedwingDogmaModule
    );
    shared.ServiceRegistry.register(SeedwingDogma);
    registerValidationChecks(SeedwingDogma);
    return { shared, SeedwingDogma };
}
